name: Simple Deploy to Cloud Run

on:
  push:
    branches: [ "main" ] # Triggers every time you push to your main branch

env:
  PROJECT_ID: jay-personal-learning  # e.g., my-sample-project
  REGION: us-central1          # e.g., us-east1
  SERVICE: simple-hello-world  # Name your service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Uses the key you saved in GitHub

      - name: Build and Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./ # Automatically uses your Dockerfile to build
